"""
Knowledge Graph Taxonomy — Node Types & Edge Types Enums
"""
import enum


class NodeType(str, enum.Enum):
    USER = "User"
    HOST = "Host"
    DEVICE = "Device"
    IP_ADDRESS = "IP_Address"
    MAC_ADDRESS = "MAC_Address"
    USB_DEVICE = "USB_Device"
    PROCESS = "Process"
    PARENT_PROCESS = "Parent_Process"
    EXECUTABLE = "Executable"
    REGISTRY_KEY = "Registry_Key"
    SERVICE = "Service"
    TASK = "Task"
    NETWORK_CONNECTION = "Network_Connection"
    FILE = "File"
    DIRECTORY = "Directory"
    EVIDENCE = "Evidence"
    NORMALIZED_EVENT = "Normalized_Event"
    CASE = "Case"
    TIMELINE_EVENT = "Timeline_Event"
    ALERT = "Alert"
    IOC = "IOC"
    DOMAIN = "Domain"
    URL = "URL"
    HASH = "Hash"
    EMAIL = "Email"
    ACCOUNT = "Account"
    SESSION = "Session"


class EdgeType(str, enum.Enum):
    LOGGED_IN_TO = "LOGGED_IN_TO"
    CONNECTED_TO = "CONNECTED_TO"
    CREATED = "CREATED"
    MODIFIED = "MODIFIED"
    DELETED = "DELETED"
    EXECUTED = "EXECUTED"
    SPAWNED = "SPAWNED"
    DOWNLOADED = "DOWNLOADED"
    UPLOADED = "UPLOADED"
    COPIED = "COPIED"
    MOVED = "MOVED"
    RENAMED = "RENAMED"
    CONNECTED = "CONNECTED"
    AUTHENTICATED = "AUTHENTICATED"
    FAILED_AUTH = "FAILED_AUTH"
    USED = "USED"
    INSERTED = "INSERTED"
    REMOVED = "REMOVED"
    ACCESSED = "ACCESSED"
    READ = "READ"
    WROTE = "WROTE"
    STARTED = "STARTED"
    STOPPED = "STOPPED"
    PERSISTED = "PERSISTED"
    COMMUNICATED_WITH = "COMMUNICATED_WITH"
    BELONGS_TO = "BELONGS_TO"
    GENERATED = "GENERATED"
    REFERENCES = "REFERENCES"
    RELATED_TO = "RELATED_TO"
